### ISSUE TITLE
move "symlink" from extension to filename?

### ISSUE THREAD

**Issue by quattlebaum** [nickzman/symboliclinker#13]
Hello all and Happy New Year.
I use a MacOS background switcher to change the desktop of my screen.

I have thousands of nicely organized photos but I want only my favorites to be part of the selected images for the background switcher. Rather than duplicate each desired image into the folder the switcher uses I can make Symlinks and move them.

SymbolicLinker adds " symlink" after the extension which means the b-s won't recognize them as links to JPGs. If I remove " symlink" they work.

The b-s also works if " symlink" is added to the end of the FileName.

I know changing the code would do this - is there any specific reason for " symlink" to be added as part of the extension?

Could this be implemented if no one else has specific need for it to come after the extension?

thank you all
qb

**Comment by nickzman** [comment]
SL tries as closely as possible to mimic the Finder's behavior when it makes an alias, and the Finder works in the same way here. It's expected that you'll move and rename the link file to something else. It's rarely helpful to keep the "symlink" filename suffix in place.

**Comment by quattlebaum** [comment]
nickzman - thank you for the quick reply. I'm using Catalina 10.15.2

Using my limited Terminal knowledge and testing the "ln -s" command the default behavior does not add " symlink" to the new item filename. In fact it adds nothing - failing as it cannot overwrite the original source filename. But you are correct as the Finder "Make Alias" does...

I'll contact the background switcher's developer and it seems this may be an issue with how it handles (or does not handle) such links.

**Comment by andrewcrook** [comment]
@quattlebaum  

> is there any specific reason for " symlink" to be added as part of the extension?

To stop duplication  and so you can identify them apart.

I just normally select a folder , make symlink , move, then rename (also removing the suffix) 
This is the correct behaviour for folders

However,I can see that this could be annoying with files and should probably add the suffix before any extension 

image.jpg -> image symlink.jpg

rather than the current 

image.jpg -> image.jpg  symlink

if you duplicate a file in finder it does the following

image.jpg -> image copy.jpg

So it should probably be made to follow the same naming rules here.

Would @nickzman  not agree?

**Comment by nickzman** [comment]
No, because the app mimics the behavior of the Make Alias command, not the Duplicate command. The Make Alias command adds the word "alias" after the original file name, and so, SL does something similar.

If you want to do something different, feel free to download the source code, and customize it as much as you want to customize it. But this is not going to change unless the Finder changes.
