### ISSUE TITLE
Cannot create file links in the SymbolicLinker folder

### ISSUE THREAD

**Issue by ninevcat** [nickzman/symboliclinker#15]
I want to create all file links when I use the SymbolicLinker Service to create the SymbolicLinker folder.
so the MUSIC application(Audirvana) can detect the original files.
Will it be supported in the next version?

**Comment by nickzman** [comment]
Sorry, I don't understand the question. You can create symbolic links to multiple files, folders, or even volumes at once by selecting multiple files/folders/volumes in the same window in the Finder.

**Comment by nickzman** [comment]
That seems like one very esoteric use case. You could just create symbolic links to everything inside a folder, then move the links to a new folder you create on your desktop or something like that.

I'm not going to add any new features to SL, since it's intended to emulate the Finder's Make Alias command, and nothing beyond that. But you can always edit the source code to do what you need it to do, and make your own binary.
